name: Build Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Xcode
      run: |
        xcodebuild clean test -workspace Siggi_iOS.xcworkspace \
        -scheme Siggi_iOS-Workspace \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
