name: Build Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Mise and Set PATH
        run: |
          curl https://mise.jdx.dev/install.sh | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      - name: Install Tuist
        run: |
          mise install tuist@3.42.2
          mise use tuist@3.42.2
    
      - name: Fetch Dependencies
        run: tuist fetch

      - name: Generate Project
        run: tuist generate
        
      - name: Build Project
        run: tuist build
