# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tuist/tuist-action@0.13.0 # This action has an issue with tuist 3.1.0, so you have to use version 3.0.1: https://github.com/tuist/tuist-action/issues/6
        with:
          command: 'fetch'
          arguments: ''
      - uses: tuist/tuist-action@0.13.0 # This action has an issue with tuist 3.1.0, so you have to use version 3.0.1: https://github.com/tuist/tuist-action/issues/6
        with:
          command: 'build'
          arguments: ''
